/**
 * Regenerates the HEARTS360 static `ds-card` metrics + facility list from
 * `src/data/facilities.ts` (same source as the embed panel).
 *
 * Usage (from repo root): `npx tsx scripts/emit-hearts360-static-ds-card.ts`
 *
 * Output: ../hearts360/overview-ds-card-district-data.generated.html
 * Paste that file’s contents over the matching block in hearts360/index.html
 * (between ds-metrics-wrap and the closing article), or diff to verify.
 */

import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { facilityToOverviewRow, getOverviewCardModel } from "../src/lib/overviewCardModel.ts";

const __dirname = dirname(fileURLToPath(import.meta.url));

function fmtDelta(delta: number): string {
  if (delta === 0) return "+0 pp";
  if (delta < 0) return `\u2212${Math.abs(delta)} pp`;
  return `+${delta} pp`;
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

/** Sparkline SVG bodies — design constants; not derived from data. */
const SPARK_SVGS = [
  `<svg
                    class="ds-spark"
                    viewBox="0 0 96 28"
                    fill="none"
                    xmlns="http://www.w3.org/2000/svg"
                    aria-hidden="true"
                  >
                    <polyline
                      points="4,7 11,7 17,6 23,9 29,8 35,11 41,12 47,14 53,15 59,16 65,17 71,18 77,20 83,21 88,22"
                      stroke="currentColor"
                      stroke-width="1.35"
                      stroke-linecap="round"
                      stroke-linejoin="round"
                    />
                    <circle class="ds-spark__dot" cx="88" cy="22" r="3" />
                  </svg>`,
  `<svg
                    class="ds-spark"
                    viewBox="0 0 96 28"
                    fill="none"
                    xmlns="http://www.w3.org/2000/svg"
                    aria-hidden="true"
                  >
                    <polyline
                      points="4,22 11,21 17,20 23,18 29,17 35,15 41,14 47,13 53,12 59,11 65,10 71,9 77,8 83,8 88,8"
                      stroke="currentColor"
                      stroke-width="1.35"
                      stroke-linecap="round"
                      stroke-linejoin="round"
                    />
                    <circle class="ds-spark__dot" cx="88" cy="8" r="3" />
                  </svg>`,
  `<svg
                    class="ds-spark"
                    viewBox="0 0 96 28"
                    fill="none"
                    xmlns="http://www.w3.org/2000/svg"
                    aria-hidden="true"
                  >
                    <polyline
                      points="4,23 11,22 17,21 23,19 29,18 35,16 41,15 47,13 53,12 59,11 65,10 71,9 77,8 83,7 88,8"
                      stroke="currentColor"
                      stroke-width="1.35"
                      stroke-linecap="round"
                      stroke-linejoin="round"
                    />
                    <circle class="ds-spark__dot" cx="88" cy="8" r="3" />
                  </svg>`,
];

function buildFragment(): string {
  const { stats, topFacilities } = getOverviewCardModel();
  const rows = topFacilities.map(facilityToOverviewRow);

  const metricCells = stats
    .map((s, i) => {
      const spark = SPARK_SVGS[i] ?? SPARK_SVGS[SPARK_SVGS.length - 1];
      return `                <div class="ds-metric">
                  <p class="ds-metric__label">${escapeHtml(s.label)}</p>
                  <p class="ds-metric__delta">${escapeHtml(fmtDelta(s.delta))}</p>
                  <p class="ds-metric__now">now <strong>${s.value}%</strong></p>
                  ${spark}
                </div>`;
    })
    .join("\n");

  const facItems = rows
    .map(
      (r) => `              <li class="ds-fac-item">
                <div class="ds-fac-row">
                  <span class="ds-fac-name">${escapeHtml(r.name)}</span>
                  <span class="ds-badge">${escapeHtml(r.badgeLabel)}</span>
                </div>
                <p class="ds-fac-desc">
                  ${escapeHtml(r.summaryLine)}
                </p>
              </li>`,
    )
    .join("\n");

  return `<!-- generated by hearts360ai/scripts/emit-hearts360-static-ds-card.ts — do not edit by hand -->
            <div class="ds-metrics-wrap">
              <div class="ds-metrics">
${metricCells}
              </div>
            </div>

            <p class="ds-fac-heading">Facilities that need attention</p>
            <ul class="ds-fac-list">
${facItems}
            </ul>
`;
}

const outPath = join(__dirname, "..", "..", "hearts360", "overview-ds-card-district-data.generated.html");
writeFileSync(outPath, buildFragment(), "utf8");
console.log("Wrote", outPath);
